---
layout: single
title: "unit5(Jupiter) Assertions Class 기본 사용법"
author_profile: true
sidebar:
  nav: "docs"
categories:
  - SpringBoot
tags:
  - SpringBoot
  - JUnit5
  - UnitTest
toc: true
toc_sticky: true
date: 2023-07-24
last_modified_at: 2023-07-24
---

### 개요

---

<span style="font-size:13pt">
Junit5(Jupiter) Assertions Class 일람<br>
org.junit.jupiter.api.Assertions 클래스 메소드에 대한 내용.
</span>
[참고사이트](https://howtodoinjava.com/junit5/junit-5-assertions-examples/)
[참고사이트2](https://juno-juno.tistory.com/79)

### Assertions.assertEquals

<span style="font-size:13pt">
기대 값 과 실제 값이 일치하는지 비교한다.<br>
int, string, double등등 여러 타입비교가 가능하다.<br>
</span>

```kotlin
    @Test
    fun assertEqualsTest() {
        var exceptedInt = 1
        var actualInt = 1
        var failureActualInt = 2

        Assertions.assertEquals(exceptedInt,actualInt)

        // failure case
        // Assertions.assertEquals(exceptedInt, failureActualInt, "test failed")
        // Assertions.assertEquals(exceptedInt, failureActualInt) { "exceptedInt, failureActualInt test failed" }
    }
```

실행 결과

```
JunitAssertionTest > assertEqualsTest() PASSED
```

<span style="font-size:13pt">
주석 처리된 // Assertions.assertEquals(exceptedInt, failureActualInt, "test failed") <br>
이 부분 대신 Assertions.assertEquals(exceptedInt, failureActualInt) { "exceptedInt, failureActualInt test failed" }를 사용한 이유는 String 대신 Supplier를 사용하기 때문이다. <br>
String으로 해도 문제 없이 돌아 가지만 Supplier를 사용하면 오류가 발생하는 순간에 해당 String연산을 하여 불필요한 연산을 줄일 수 있다. <br>
이후 서술할 내용에서 실패 시 메시지를 낼 수 있는 부분은 동일하기에 생략한다. <br>
</span>

### Assertions.assertArrayEquals

<span style="font-size:13pt">
두 배열의 기대 값과 실제 값이 같은지를 비교한다.<br>
assertEquals와 마찬가지로 int, string, double등등 여러 타입 배열의 비교가 가능하다.<br>
kotlin은 null을 넣을 경우 컴파일 에러가 난다.<br>
java의 경우 두 배열이 null이라도 같다고 간주한다.<br>
</span>

```kotlin
    @Test
    fun assertArrayEqualsTest() {
        var expectedArr: CharArray? = "kotlin".toCharArray()
        var actualArr: CharArray? = charArrayOf('k', 'o', 't', 'l', 'i', 'n')
        var failureActualArr: CharArray? = "java".toCharArray()
        Assertions.assertArrayEquals(expectedArr, actualArr)

        // failure case
        // Assertions.assertArrayEquals(expectedArr, failureActualArr)

        expectedArr = null
        actualArr = null
        // Assertions.assertArrayEquals(expectedArr, actualArr)
    }
```

실행 결과

```
JunitAssertionTest > assertArrayEqualsTest() PASSED
```

### Assertions.assertIterableEquals

<span style="font-size:13pt">
두 Iterable의 기대 값과 실제 값이 같은지를 비교한다.<br>
Collection의 종류는 상관 없지만 순서는 동일해야 한다.<br>
</span>

```kotlin
    @Test
    fun assertIterableEqualsTest() {
        val expectedIterable: ArrayList<String?> = arrayListOf("Java", "Junit", "Test")
        val actualIterable: LinkedList<String?> = LinkedList(listOf("Java", "Junit", "Test"))
        val actualIterableSet = setOf<String?>("Java", "Junit", "Test")

        Assertions.assertIterableEquals(expectedIterable, actualIterable)
        Assertions.assertIterableEquals(expectedIterable, actualIterableSet)

        val failureActualArr: ArrayList<String?> = arrayListOf("Junit", "Java", "Test")
        val failureActualArr2: ArrayList<String?> = arrayListOf("kotlin", "Junit", "Test")
        // failure case
        // Assertions.assertIterableEquals(expectedIterable, failureActualArr)
        // Assertions.assertIterableEquals(expectedIterable, failureActualArr2)
    }
```

실행 결과

```
JunitAssertionTest > assertIterableEqualsTest() PASSED
```

### Assertions.assertLinesMatch

<span style="font-size:13pt">
두 List나 stream의 string이 동일 한지 비교한다.<br>
</span>

```kotlin
    @Test
    fun assertLinesMatchTest() {
        val expectedList = listOf<String?>("one", "[0-7]", ">> skip >>", "\\d+")
        val actualList = listOf<String?>("one", "5", "two", "three", "four", "9")

        Assertions.assertLinesMatch(expectedList, actualList)
    }
```

실행 결과

```
JunitAssertionTest > assertLinesMatchTest() PASSED
```

<span style="font-size:13pt">
assertIterableEquals와 비슷해 보이지만 조금 다르다.<br>
</span>

1. 기대 값과 실제 값을 equals로 비교 한 후 true면 다음 pair로 넘어간다.
   ※여기까지는 assertIterableEquals와 동일하다.
2. 내용이 true가 아니면 String.matches로 정규식으로 비교하고 true면 다음 pair로 넘어간다.
3. expected 라인이 fast-forward marker라면 1로 넘어간다.

<span style="font-size:13pt">
Fast-forward marker란 git병합에서 많이 보던 >>>>를 뜻한다.<br>
\>> 와 >> 사이에 4자이상의 문자열이 포함한다면 다음 expected와 일치하는 actual이 나올떄까지 스킵한다.<br>
실제 실행 결과 two three four는 넘어가고 \\d+정규식을 체크했다.<br>
참고로 \d는 0-9의 숫자고 +는 1개 이상 \가 하나 더 붙은 이유는 코틀린이 문자열로 인식하게끔 하기 위해서이다.<br>
즉 0-9의 1자리수 이상의 숫자의 정규식이다.<br>
Files.lines()등을 이용해서 파일을 읽어 들이고 불필요한 부분은 Fast-forward marker로 넘겨서 빠른 유닛 테스트가 가능해진다.<br>
</span>

### Assertions.assertNotNull and Assertions.assertNull

<span style="font-size:13pt">
실제 값의 객체가 null인지 null이 아닌지 체크한다.<br>
Any(Object)형으로 체크한다.<br>
</span>

```kotlin
    @Test
    fun assertNotNullTest() {
        val actualNotNullValue = "String"

        Assertions.assertNotNull(actualNotNullValue)
    }

    @Test
    fun assertNullTest() {
        val actualNullValue = null

        Assertions.assertNull(actualNullValue)
    }
```

실행 결과

```
JunitAssertionTest > assertNotNullTest() PASSED
JunitAssertionTest > assertNullTest() PASSED
```

### Assertions.assertNotSame and Assertions.assertSame

<span style="font-size:13pt">
두 객체의 기대 값과 실제 값이 동일 한 객체인지 아닌지 체크한다.<br>
</span>

```kotlin
    @Test
    fun assertNotSameTest() {
        val expectedObject = "any"
        val clone = expectedObject
        val actualObject = "object"

        // pass
        Assertions.assertNotSame(expectedObject, actualObject)

        // fail
        // Assertions.assertNotSame(expectedObject, clone, "fail case")
    }

    @Test
    fun assertSameTest() {
        val expectedObject = "any"
        val clone = expectedObject
        val actualObject = "object"

        // pass
        Assertions.assertSame(expectedObject, clone)

        // fail
        // Assertions.assertSame(expectedObject, actualObject, "fail case")
    }
```

실행 결과

```
JunitAssertionTest > assertNotSameTest() PASSED
JunitAssertionTest > assertSameTest() PASSED
```

### Assertions.assertTimeout and Assertions.assertTimeoutPreemptively

<span style="font-size:13pt">
메소드의 실행 완료 시간이 정해진 시간 내에 완료가 되는지 확인한다.<br>
assertTimeout는 메소드가 전부 실행이 완료 되어야 테스트가 완료 되고<br>
assertTimeoutPreemptively는 정해진 시간을 초과하면 테스트가 종료되는 차이점이 있다.<br>
</span>

```kotlin
    @Test
    fun assertTimeoutTest() {
        // pass case
        Assertions.assertTimeout<String>(Duration.ofMinutes(1)) {
            return@assertTimeout "result"
        }

        // fail case
        /*
        Assertions.assertTimeout<String>(Duration.ofMillis(100)) {
            Thread.sleep(500)
            return@assertTimeout "result"
        }
        */
    }

    @Test
    fun assertTimeoutPreemptivelyTest() {
        Assertions.assertTimeoutPreemptively<String>(Duration.ofMillis(100)) {
            return@assertTimeoutPreemptively "result"
        }
        /*
        Assertions.assertTimeoutPreemptively<String>(Duration.ofMillis(100)) {
            Thread.sleep(500)
            return@assertTimeoutPreemptively "result"
        }
        */
    }
```

실행 결과

```
JunitAssertionTest > assertTimeoutTest() PASSED
JunitAssertionTest > assertTimeoutPreemptivelyTest() PASSED
```

### Assertions.assertTrue and Assertions.assertFalse

<span style="font-size:13pt">
assertTrue 인자가 true면 다음으로<br>
assertFalse 인자가 false면 다음으로 넘어간다.<br>
</span>

```kotlin
    @Test
    fun assertTrueTest() {
        // pass case
        Assertions.assertTrue("A" == "A")

        // fail case
        // Assertions.assertTrue("A" == "B")
    }

    @Test
    fun assertFalseTest() {
        // pass case
        Assertions.assertFalse("A" == "B")

        // fail case
        // Assertions.assertFalse("A" == "A")
    }
```

실행 결과

```
JunitAssertionTest > assertTrueTest() PASSED
JunitAssertionTest > assertFalseTest() PASSED
```

### Assertions.assertThrows

<span style="font-size:13pt">
첫번째 인자의 예외와 두번째 인자의 예외가 같은지 검사한다.<br>
첫번째 인자는 기대값이고 두번째 인자는 실제 값이다.<br>
</span>

```kotlin
    @Test
    fun assertThrowsTest() {
        // pass case
        Assertions.assertThrows(NullPointerException::class.java) { throwTest() }
        // fail case
        // Assertions.assertThrows(NullPointerException::class.java) { throwTestFail() }
    }

    fun throwTest() {
        var testString: String? = null
        try {
            testString!!.length
        } catch (e: NullPointerException) {
            throw NullPointerException("null")
        }
    }

    fun throwTestFail() {
        var testStringArr = arrayOf("1", "2", "3", "4", "5")
        try {
            testStringArr[5]
        } catch (e: IndexOutOfBoundsException) {
            throw IndexOutOfBoundsException("IndexOutOfBounds")
        }
    }
```

실행 결과

```
JunitAssertionTest > assertThrowsTest() PASSED
```

### Assertions.fail

<span style="font-size:13pt">
테스트에 실패한다.<br>
무엇에 쓰는지는 잘 모르지만 로직이 통과하여 fail까지 도달할 경우 실패하는 케이스 등으로 쓰일지도 모르겠다.<br>
</span>

```kotlin
    @Test
    fun failTest() {
        try {
            throwTestFail()
            Assertions.fail<Any>("fail")
        } catch (e: IndexOutOfBoundsException) {
            Assertions.assertTrue(true)
        }
    }

    // fail case
    @Test
    fun failTestFail() {
        try {
            throwTestFail()
            Assertions.fail<Any>("fail")
        } catch (e: NullPointerException) {
            Assertions.assertTrue(true)
        }
    }

    fun throwTest() {
        var testString: String? = null
        try {
            testString!!.length
        } catch (e: NullPointerException) {
            throw NullPointerException("null")
        }
    }

    fun throwTestFail() {
        var testStringArr = arrayOf("1", "2", "3", "4", "5")
        try {
            testStringArr[5]
        } catch (e: IndexOutOfBoundsException) {
            throw IndexOutOfBoundsException("IndexOutOfBounds")
        }
    }
```

실행 결과

```
JunitAssertionTest > failTest() PASSED
JunitAssertionTest > failTestFail() FAILED
    java.lang.IndexOutOfBoundsException: IndexOutOfBounds
```

### Assertions.assertAll

<span style="font-size:13pt">
Assertions를 전부 실행한다.<br>
assertXXX의 경우 도중에 실패하면 실행을 멈추지만 assertAll은 도중에 실패가 되어도 무시하고 전부 실행한다.<br>
아래 로직을 실행하면 Assertions.assertThrows(NullPointerException::class.java) { throwTestFail() }에서 실패하지만<br>
가장 아래의 Assertions.assertTrue(false)까지 실행하여 총 3개가 실패했다고 로그에 출력된다.<br>
</span>

```kotlin
    @Test
    fun assertAllTest() {
        Assertions.assertAll(
            { Assertions.assertThrows(NullPointerException::class.java) { throwTestFail() } },
            { Assertions.assertTrue(false) },
            { Assertions.assertTrue(true) },
            { Assertions.assertTrue(true) },
            { Assertions.assertTrue(false) }
        )
    }
```

실행 결과

```
JunitAssertionTest > assertAllTest() FAILED
    org.gradle.internal.exceptions.DefaultMultiCauseException: Multiple Failures (3 failures)
```
